# Generated by Django 5.0.3 on 2024-04-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_remove_bid_auction_remove_category_auctions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.TextField(blank=True, default='https://www.freeiconspng.com/thumbs/no-image-icon/no-image-icon-15.png', null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
